### ISSUE TITLE
Switching to desktop site fails on journey page

### ISSUE THREAD

**Issue by Mimoja** [derf/travelynx#36] opened 2020-01-14 16:33 UTC
When tapping the "Show Desktop Version" button on mobile you get redirected into an error

**Comment by Mimoja** [comment] 2020-01-14 16:34
From
![Screenshot_20200114-173135](https://user-images.githubusercontent.com/10907336/72362787-10ccd180-36f4-11ea-9b7c-a2eeba873ee4.jpg)

To
![Screenshot_20200114-173120](https://user-images.githubusercontent.com/10907336/72362747-feeb2e80-36f3-11ea-8e6f-e9aff70d0bef.jpg)

**Comment by derf** [comment] 2020-01-19 18:15
`/journey/edit` is an intermediate page which immediately redirects to `/journey/$number`. I wonder why the browser chose to go there when switching between desktop and mobile version, even though the mobile page was `/journey/10308`

**Comment by derf** [comment] 2024-08-24 08:07
couldn't reproduce, assuming that it's fixed by now

**Closed by derf** 2024-08-24 08:07 UTC
Labels: bug
